In [2]:
import read_symbol_df

dfs = read_symbol_df.tick_df(["/tmp/test.tick", "rb2305"])

r = read_symbol_df.sim(dfs[0])
r

 0  rb2305 volume:  507400, step     0.000 range          0

/Users/liuzhe/github/DPL_study/nbs/read_symbol_df.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ret.loc[:,'isb'] = ret.apply(lambda row: row['p'] == row['b1'], axis=1)
/Users/liuzhe/github/DPL_study/nbs/read_symbol_df.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ret.loc[:,'dv'] = ret.v.diff()

              p       v      a1  av1      b1  bv1    isb      dv
1655     4261.0   11964  4262.0   72  4261.0  328   True  1642.0
1999     4259.0   14002  4259.0   13  4257.0    2  False  2038.0
2384     4259.0   16625  4259.0  105  4257.0    3  False  2623.0
2853     4259.0   17341  4258.0   31  4257.0    1  False   716.0
3195     4259.0   18428  4260.0  327  4259.0  310   True  1087.0
...         ...     ...     ...  ...     ...  ...    ...     ...
2381837  4250.0  517628  4251.0   69  4250.0   28   True    90.0
2382013  4250.0  517683  4250.0    8  4249.0   20  False    55.0
2382159  4248.0  517709  4249.0    2  4248.0   38   True    26.0
2382266  4249.0  517714  4249.0    4  4248.0   39  False     5.0
2382408  4250.0  517722  4250.0   23  4248.0   48  False     8.0

[14331 rows x 8 columns]